keys:
  - &primary age1zpsu56zn0xncqrunf0y62fupd3cjrr9qp0nazjram39pwpezr5mstnyx60
  - &telariel age1czf562frvwgus6xmhj4x6vth3v47r93dzxlfh4td6yfaz9vagc8qhcg633
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: iteration110/secrets.yaml$
    key_groups:
      - age:
        - *telariel
