# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 8 2 0
label A0 = "Done"
label B0 = "Previous"
label C0 = "Dendritic"
label A1 = "x"
leftstring B1 = "fish"
leftstring C1 = "cli/fish"
leftstring B2 = "foot"
leftstring C2 = "cli/foot"
goto A2
