{
  pkgs,
  config,
  lib,
  username,
  ...
}: {
  imports = [
    ./base
    ../base.nix

    ./desktop
    # ./system.nix
  ];

  # NixOs's configuration for Wayland base window manager
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-wlr
    ];
  };

  services = {
    xserver.enable = false; # Disable xorg server
    greetd = {
      enable = true;
      settings = {
        default_session = {
          # Wayland Desktop Manager is installd only for user rail via home-manager
          user = username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor (sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          command = "$HOME/.wayland-session";
          # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
        };
      };
    };
  };

  security.pam.services.swaylock = {};
}

